name: Test Model u22

on:
  push:
    branches:
      - main

jobs:
  test-model:
    runs-on: ubuntu-22.04-arm-os # Custom ARM64 runner
    container:
      image: armswdev/pytorch-arm-neoverse:r24.07-torch-2.3.0-openblas
      options: --user 1001
    name: Test the Model
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Latest version
      - name: Install dependencies
        run: |
          pip install torch==2.4.0 torchvision==0.15.0
      - name: Run testing script
        run: python scripts/test_model.py
