name: Test Model

on:
  workflow_run:
    workflows: ["Train Model"]
    types:
      - completed

jobs:
  test-model:
    runs-on: linux-arm-runner # Custom ARM64 runner
    name: Test the Model
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Latest version
      - name: Install pip3
        run: |
          echo "apt get update"
          sudo apt-get update
          echo "pip3 install"
          sudo apt install python3-pip
      - name: Install dependencies
        run: |
          pip install torch==2.4.0 torchvision==0.15.0

      - name: Run testing script
        run: python scripts/test_model.py
