name: Train Model u22

on:
  push:
    branches:
      - main

jobs:
  train-model:
    name: Train the Model
    runs-on: ubuntu-22.04-arm-os # Custom ARM64 runner
    container:
      image: armswdev/pytorch-arm-neoverse:r24.07-torch-2.3.0-openblas
    steps:
      - name: Pip list
        run: pip list
      - name: Checkout code
        uses: actions/checkout@v4
      #- name: Run training script
      #  run: python scripts/train_model.py
      #- name: 'Upload Artifact'
      #  uses: actions/upload-artifact@v4
        with:
          name: traffic_sign_net
          path: ${{ github.workspace }}/models/traffic_sign_net.pth
          retention-days: 30