name: Reduced epoch training and test comparision

on:
  workflow_dispatch:

jobs:
  train-model:
    name: Run comparison script
    runs-on: ubuntu-22.04-arm-os # Custom ARM64 runner
    container:
      image: armswdev/pytorch-arm-neoverse:r24.07-torch-2.3.0-onednn-acl
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run training script
        run: python scripts/train_test_compare.py
