name: Train Model

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: linux-arm-runner # Custom ARM64 runner
    name: Train the Model
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install pip
        run: |
          apt-get install python-pip
      - name: Install dependencies
        run: |
          pip install torch==2.4.0 torchvision==0.15.0

      - name: Run training script
        run: python scripts/train_model.py
